name:                aoc2019
version:             0.1.0.0
github:              "hmpcabral/aoc2019"
license:             BSD3
author:              "Henrique Cabral"
maintainer:          "henriquempcabral@gmail.com"
copyright:           "2019 Henrique Cabral"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/hmpcabral/aoc2019#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- split
- containers
- lens
- linear

library:
  source-dirs: src

executables:
  day01-exe:
    main:                app/Day01.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

  day02-exe:
    main:                app/Day02.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

  day03-exe:
    main:                app/Day03.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

  day04-exe:
    main:                app/Day04.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

  day05-exe:
    main:                app/Day05.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

  day06-exe:
    main:                app/Day06.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

  day07-exe:
    main:                app/Day07.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

  day08-exe:
    main:                app/Day08.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

  day09-exe:
    main:                app/Day09.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

  day10-exe:
    main:                app/Day10.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

tests:
  aoc2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019
    - hspec
    - QuickCheck
