name:                aoc2019
version:             0.1.0.0
github:              "hmpcabral/aoc2019"
license:             BSD3
author:              "Henrique Cabral"
maintainer:          "henriquempcabral@gmail.com"
copyright:           "2019 Henrique Cabral"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/hmpcabral/aoc2019#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  day01-exe:
    main:                app/Day01.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

tests:
  aoc2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019
    - hspec
    - QuickCheck
